CREATE TABLE IF NOT EXISTS "postgres"."medical_bills".admissions (
ADMISSION_ID INT,
PATIENT_ID VARCHAR(100),
ADMISSION_DATE DATE,
DISCHARGE_DATE DATE,
DEPARTMENT VARCHAR(200),
ATTENDING_DOCTOR_ID VARCHAR(100)
);


CREATE TABLE IF NOT EXISTS "postgres"."medical_bills".billing (
BILLING_ID INT,
ADMISSION_ID INT,
CHARGE_TYPE VARCHAR(100),
AMOUNT VARCHAR(50),
PAYMENT_STATUS VARCHAR(100),
PAYMENT_DATE DATE
);


CREATE TABLE IF NOT EXISTS "postgres"."medical_bills" .diagnosis (
DIAGNOISIS_ID INT,
ADMISSION_ID INT,
ICD_CODE VARCHAR(100),
DIAGNOSIS VARCHAR(100),
SERVERITY VARCHAR(100)

);


CREATE TABLE IF NOT EXISTS "postgres"."medical_bills".patients (
PATIENT_ID INT,
FULL_NAME VARCHAR(100),
DATE_OF_BIRTH DATE,
PHONE VARCHAR(20),
EMAIL VARCHAR(100),
ADDRESS VARCHAR(100),
INSURANCE_PROVIDER VARCHAR(100)

);
